# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    
    # Java
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
         java-version: 11
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD
    
    # Build Maven
    - name: Build with Maven
      run: mvn -B package verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file pom.xml
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # Publish to maven central
    - name: Publish package
      if: startsWith(github.ref, 'refs/tags/')
      run: mvn -B deploy
      env:
         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

    # Create GitHub release
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ github.ref }}
         release_name: v${{ steps.versionName.outputs.versionName }}
         draft: true
         prerelease: true
    
